export const places = [
  {
    label: "Toshkent viloyati",
    items: [
      { value: "toshkent", label: "Toshkent shahri" },
      { value: "bekobod", label: "Bekobod tumani" },
      { value: "bishkek", label: "Bishkek tumani" },
      { value: "chilonzor", label: "Chilonzor tumani" },
      { value: "yangiyo'l", label: "Yangiyo'l tumani" },
      { value: "yashnobod", label: "Yashnobod tumani" },
      { value: "olmazor", label: "Olmazor tumani" },
      { value: "uchtepa", label: "Uchtepa tumani" },
      { value: "uchqo'rg'on", label: "Uchqo'rg'on tumani" },
      { value: "shaikhontohur", label: "Shaikhontohur tumani" },
      { value: "yakkasaroy", label: "Yakkasaroy tumani" },
      { value: "yunusobod", label: "Yunusobod tumani" },
      { value: "zarafshon", label: "Zarafshon tumani" },
    ],
  },
  {
    label: "Andijon viloyati",
    items: [
      { value: "andijon", label: "Andijon shahri" },
      { value: "asaka", label: "Asaka tumani" },
      { value: "boburshoh", label: "Boburshoh tumani" },
      { value: "buloqboshi", label: "Buloqboshi tumani" },
      { value: "igat", label: "Igat tumani" },
      { value: "jalolquduq", label: "Jalolquduq tumani" },
      { value: "margilon", label: "Marg'ilon shahri" },
      { value: "oxunboboyev", label: "O'xunboboyev tumani" },
      { value: "paxtachi", label: "Paxtachi tumani" },
      { value: "shahrixon", label: "Shahrixon tumani" },
      { value: "uchko'prik", label: "Uchko'prik tumani" },
      { value: "xonobod", label: "Xonobod tumani" },
    ],
  },
  {
    label: "Buxoro viloyati",
    items: [
      { value: "buxoro", label: "Buxoro shahri" },
      { value: "romitan", label: "Romitan tumani" },
      { value: "gijduvon", label: "G'ijduvon tumani" },
      { value: "vobkent", label: "Vobkent tumani" },
      { value: "jondor", label: "Jondor tumani" },
      { value: "kagan", label: "Kagan tumani" },
      { value: "karakul", label: "Karakul tumani" },
      { value: "peshku", label: "Peshku tumani" },
      { value: "qorako'lpoyon", label: "Qorako'l poyon tumani" },
      { value: "shofirkon", label: "Shofirkon tumani" },
      { value: "xorazm", label: "Xorazm tumani" },
      { value: "g'allaorol", label: "G'allaorol tumani" },
      { value: "qorao'zak", label: "Qorao'zak tumani" },
      { value: "pahtachi", label: "Pahtachi tumani" },
      { value: "peshku", label: "Peshku tumani" },
      { value: "romitan", label: "Romitan tumani" },
      { value: "vobkent", label: "Vobkent tumani" },
      { value: "yangiobod", label: "Yangiobod tumani" },
    ],
  },
  {
    label: "Jizzax viloyati",
    items: [
      { value: "jizzax", label: "Jizzax shahri" },
      { value: "yangiobod", label: "Yangiobod tumani" },
      { value: "g'allaorol", label: "G'allaorol tumani" },
      { value: "mardxon", label: "Mardxon tumani" },
      { value: "zafarobod", label: "Zafarobod tumani" },
      { value: "paxtakor", label: "Paxtakor tumani" },
      { value: "forish", label: "Forish tumani" },
      { value: "do'stlik", label: "Do'stlik tumani" },
      { value: "jabborrasulov", label: "Jabborrasulov tumani" },
      { value: "zomin", label: "Zomin tumani" },
      { value: "pakhtachi", label: "Pakhtachi tumani" },
      { value: "shaqrisabz", label: "Shaqrisabz tumani" },
      { value: "dustobod", label: "Dustobod tumani" },
    ],
  },
  {
    label: "Qashqadaryo viloyati",
    items: [
      { value: "qarshi", label: "Qarshi shahri" },
      { value: "shahrisabz", label: "Shahrisabz shahri" },
      { value: "nishon", label: "Nishon tumani" },
      { value: "kasbi", label: "Kasbi tumani" },
      { value: "kitob", label: "Kitob tumani" },
      { value: "mirishkor", label: "Mirishkor tumani" },
      { value: "qamashi", label: "Qamashi tumani" },
      { value: "chiroqchi", label: "Chiroqchi tumani" },
      { value: "yakkabog'", label: "Yakkabog' tumani" },
      { value: "dehkanobod", label: "Dehkanobod tumani" },
      { value: "kamashi", label: "Kamashi tumani" },
      { value: "g'uzor", label: "G'uzor tumani" },
    ],
  },
  {
    label: "Navoiy viloyati",
    items: [
      { value: "navoiy", label: "Navoiy shahri" },
      { value: "navbahor", label: "Navbahor tumani" },
      { value: "karmana", label: "Karmana tumani" },
      { value: "khatirchi", label: "Khatirchi tumani" },
      { value: "hojai", label: "Hojai tumani" },
      { value: "moynoq", label: "Moynoq tumani" },
    ],
  },
  {
    label: "Namangan viloyati",
    items: [
      { value: "namangan", label: "Namangan shahri" },
      { value: "chust", label: "Chust tumani" },
      { value: "uchkurgan", label: "Uchkurgan tumani" },
      { value: "yangikurgan", label: "Yangikurgan tumani" },
      { value: "to'raqo'rg'on", label: "To'raqo'rg'on tumani" },
      { value: "norin", label: "Norin tumani" },
      { value: "paxtachi", label: "Paxtachi tumani" },
      { value: "naryn", label: "Naryn tumani" },
      { value: "chartaq", label: "Chartaq tumani" },
      { value: "toshloq", label: "Toshloq tumani" },
      { value: "uchqo'rg'on", label: "Uchqo'rg'on tumani" },
    ],
  },
  {
    label: "Samarqand viloyati",
    items: [
      { value: "samarqand", label: "Samarqand shahri" },
      { value: "bulung'ur", label: "Bulung'ur tumani" },
      { value: "jambay", label: "Jambay tumani" },
      { value: "ishoqar", label: "Ishoqar tumani" },
      { value: "ishtixon", label: "Ishtixon tumani" },
      { value: "kattaqo'rg'on", label: "Kattaqo'rg'on tumani" },
      { value: "nasaf", label: "Nasaf tumani" },
      { value: "nurobod", label: "Nurobod tumani" },
      { value: "pakhtachi", label: "Pakhtachi tumani" },
      { value: "payariq", label: "Payariq tumani" },
      { value: "samarkand", label: "Samarkand tumani" },
      { value: "taylak", label: "Taylak tumani" },
      { value: "urgut", label: "Urgut tumani" },
      { value: "urgench", label: "Urgench tumani" },
    ],
  },
  {
    label: "Sirdaryo viloyati",
    items: [
      { value: "gulistan", label: "Guliston shahri" },
      { value: "bayavut", label: "Bayavut tumani" },
      { value: "bo'ston", label: "Bo'ston tumani" },
      { value: "farish", label: "Farish tumani" },
      { value: "guliston", label: "Guliston tumani" },
      { value: "mirzaabad", label: "Mirzaabad tumani" },
      { value: "saykhunabad", label: "Sayhunobod tumani" },
      { value: "sirdaryo", label: "Sirdaryo tumani" },
    ],
  },
  {
    label: "Surxondaryo viloyati",
    items: [
      { value: "termiz", label: "Termiz shahri" },
      { value: "angor", label: "Angor tumani" },
      { value: "baysun", label: "Baysun tumani" },
      { value: "denov", label: "Denov tumani" },
      { value: "muzrabot", label: "Muzrabot tumani" },
      { value: "qiziriq", label: "Qiziriq tumani" },
      { value: "sariosiyo", label: "Sariosiyo tumani" },
      { value: "shargun", label: "Shargun tumani" },
      { value: "termiz", label: "Termiz tumani" },
      { value: "uzun", label: "Uzun tumani" },
    ],
  },
  {
    label: "Farg'ona viloyati",
    items: [
      { value: "farg'ona", label: "Farg'ona shahri" },
      { value: "beshariq", label: "Beshariq tumani" },
      { value: "bag'dod", label: "Bag'dod tumani" },
      { value: "furqat", label: "Furqat tumani" },
      { value: "qo'qon", label: "Qo'qon tumani" },
      { value: "quva", label: "Quva tumani" },
      { value: "marg'ilon", label: "Marg'ilon tumani" },
      { value: "qurama", label: "Qurama tumani" },
      { value: "so'x", label: "So'x tumani" },
      { value: "uvay", label: "Uvay tumani" },
      { value: "yozyovon", label: "Yozyovon tumani" },
    ],
  },
  {
    label: "Xorazm viloyati",
    items: [
      { value: "urganch", label: "Urganch shahri" },
      { value: "qo'ng'irot", label: "Qo'ng'irot tumani" },
      { value: "bog'ot", label: "Bog'ot tumani" },
      { value: "gurlan", label: "Gurlan tumani" },
      { value: "hazorasp", label: "Hazorasp tumani" },
      { value: "kushkupir", label: "Kushkupir tumani" },
      { value: "shovot", label: "Shovot tumani" },
      { value: "xonqa", label: "Xonqa tumani" },
      { value: "yanguyul", label: "Yanguyul tumani" },
    ],
  },
];
